const dayColours = {1:'#d94f33',2:'#0f766e',3:'#7c3aed',4:'#b7791f'};
const hotel = { lat:25.04618, lng:121.51476 };
const tripDays = [
{day:1,label:'Fri 20 Aug',title:'Arrival, Dadaocheng & Ningxia',transport:'Airport MRT + walking',distance:'Gentle arrival day',stops:[
{time:'11:45',name:'Taoyuan International Airport',lat:25.0777,lng:121.2328,duration:'Arrival',type:'Transport',notes:'Clear immigration, collect luggage and follow signs to the Airport MRT. Buy one EasyCard each and keep a small cash reserve for food stalls.',official:'https://www.taoyuan-airport.com/',maps:'https://www.google.com/maps/search/?api=1&query=Taoyuan+International+Airport'},
{time:'13:15',name:'Airport MRT to A1 Taipei Main Station',lat:25.04915,lng:121.51415,duration:'35–40 min',type:'Transport',notes:'Take the express train and use lifts with luggage. Do not schedule anything time-critical before 14:30.',official:'https://www.tymetro.com.tw/tymetro-new/en/_pages/travel-guide/timetable.php',maps:'https://www.google.com/maps/search/?api=1&query=A1+Taipei+Main+Station'},
{time:'14:10',name:'Roaders Plus Hotel Taipei Station',lat:25.04618,lng:121.51476,duration:'Check-in',type:'Hotel',notes:'Drop luggage or check in. Refill water and reset before heading out.',official:'https://roadersplushotel.com/en/',maps:'https://www.google.com/maps/search/?api=1&query=Roaders+Plus+Hotel+Taipei+Station'},
{time:'14:45',name:'Lao Shan Dong Homemade Noodles',lat:25.0467,lng:121.5105,duration:'60 min',type:'Food',notes:'A convenient first meal near Taipei Main Station. Share beef noodles, dumplings and braised side dishes rather than over-ordering.',maps:'https://www.google.com/maps/search/?api=1&query=Lao+Shan+Dong+Homemade+Noodles+Taipei'},
{time:'16:00',name:'North Gate & old railway district',lat:25.04769,lng:121.51165,duration:'25 min',type:'Sight',notes:'A short architectural stop that naturally leads toward Dihua Street. If the weather is brutal, take a short taxi onward.',official:'https://www.travel.taipei/en/attraction/details/429',maps:'https://www.google.com/maps/search/?api=1&query=North+Gate+Taipei'},
{time:'16:35',name:'Dihua Street',lat:25.0556,lng:121.5092,duration:'100 min',type:'Shopping',notes:'Prioritise tea, ceramics, textiles, pantry goods and independent design stores. This is a better gift-shopping area than generic mall chains.',official:'https://www.travel.taipei/en/attraction/details/1686',maps:'https://www.google.com/maps/search/?api=1&query=Dihua+Street+Taipei'},
{time:'18:15',name:'Dadaocheng Wharf',lat:25.0568,lng:121.5072,duration:'40 min',type:'Sight',notes:'Use this as a sunset and river-breeze pause. Rain plan: skip the wharf and spend longer in Dihua cafés and shops.',official:'https://www.travel.taipei/en/attraction/details/1573',maps:'https://www.google.com/maps/search/?api=1&query=Dadaocheng+Wharf'},
{time:'19:10',name:'Ningxia Night Market',lat:25.0555,lng:121.5153,duration:'90 min',type:'Food',notes:'Share five or six small items instead of buying full portions at every stall. Priorities: oyster omelette, braised pork rice, taro, grilled squid and peanut ice-cream roll.',official:'https://www.travel.taipei/en/attraction/details/1689',maps:'https://www.google.com/maps/search/?api=1&query=Ningxia+Night+Market'},
{time:'21:00',name:'Return to Roaders Plus',lat:25.04618,lng:121.51476,duration:'Rest',type:'Hotel',notes:'Stop while the day still feels good. Arrival day is not the time to prove athletic character.',official:'https://roadersplushotel.com/en/',maps:'https://www.google.com/maps/search/?api=1&query=Roaders+Plus+Hotel+Taipei+Station'}]},
{day:2,label:'Sat 21 Aug',title:'Old Taipei, creative districts & design shopping',transport:'MRT + walking',distance:'Full but geographically ordered',stops:[
{time:'08:00',name:'Taiwanese breakfast near the hotel',lat:25.0463,lng:121.5158,duration:'45 min',type:'Food',notes:'Choose a nearby local breakfast shop for soy milk, dan bing, turnip cake or fan tuan. This protects the morning from famous-shop queues.',maps:'https://www.google.com/maps/search/?api=1&query=Taiwanese+breakfast+near+Taipei+Main+Station'},
{time:'09:00',name:'Lungshan Temple',lat:25.0372,lng:121.4999,duration:'50 min',type:'Sight',notes:'Go early for cooler air and a calmer visit. Observe respectfully and avoid blocking worshippers for photographs.',official:'https://www.travel.taipei/en/attraction/details/487',maps:'https://www.google.com/maps/search/?api=1&query=Lungshan+Temple+Taipei'},
{time:'10:00',name:'Bopiliao Historic Block',lat:25.0366,lng:121.5030,duration:'55 min',type:'Heritage',notes:'Brick arcades, preserved shop-houses and early Taipei urban texture. Saturday is deliberate because the centre is currently closed on Mondays.',official:'https://www.travel.taipei/en/attraction/details/506',maps:'https://www.google.com/maps/search/?api=1&query=Bopiliao+Historic+Block'},
{time:'11:20',name:'Ximending & The Red House',lat:25.0421,lng:121.5069,duration:'140 min',type:'Shopping',notes:'Browse streetwear, sneakers, character goods and local creative brands, then have an early lunch. Saturday is preferable because The Red House is currently closed on Mondays.',official:'https://www.redhouse.taipei/',maps:'https://www.google.com/maps/search/?api=1&query=Ximending+The+Red+House'},
{time:'14:00',name:'Chiang Kai-shek Memorial Hall',lat:25.0346,lng:121.5219,duration:'60 min',type:'Sight',notes:'Focus on Liberty Square, the theatre façades and the main hall. If heat or rain is draining energy, make this the first optional cut.',official:'https://www.travel.taipei/en/attraction/details/445',maps:'https://www.google.com/maps/search/?api=1&query=Chiang+Kai-shek+Memorial+Hall'},
{time:'15:20',name:'Yongkang Street tea & dessert',lat:25.0329,lng:121.5290,duration:'75 min',type:'Food',notes:'Use this as a seated recovery stop for tea, mango ice, coffee or a light snack. Avoid joining a queue longer than 25 minutes.',official:'https://www.travel.taipei/en/attraction/details/1712',maps:'https://www.google.com/maps/search/?api=1&query=Yongkang+Street+Taipei'},
{time:'17:00',name:'Huashan 1914 Creative Park',lat:25.0442,lng:121.5294,duration:'110 min',type:'Design',notes:'Check the 2027 exhibition calendar before travel. Prioritise temporary exhibitions and design stores rather than walking every building by default.',official:'https://www.huashan1914.com/w/huashan1914_en/index',maps:'https://www.google.com/maps/search/?api=1&query=Huashan+1914+Creative+Park'},
{time:'19:15',name:'Zhongshan & Chifeng Street',lat:25.0536,lng:121.5201,duration:'120 min',type:'Shopping',notes:'Finish with independent labels, stationery, vintage-industrial shops, cafés and dinner. This is the strongest design-shopping zone in the plan.',official:'https://www.travel.taipei/en/attraction/details/2433',maps:'https://www.google.com/maps/search/?api=1&query=Chifeng+Street+Taipei'},
{time:'21:30',name:'Return to Roaders Plus',lat:25.04618,lng:121.51476,duration:'Rest',type:'Hotel',notes:'It is close enough for MRT, walking or a short taxi depending on energy and rain.',official:'https://roadersplushotel.com/en/',maps:'https://www.google.com/maps/search/?api=1&query=Roaders+Plus+Hotel+Taipei+Station'}]},
{day:3,label:'Sun 22 Aug',title:'Private Shifen, coast viewpoints & Jiufen',transport:'Private driver only',distance:'Approx. 10 hours',stops:[
{time:'08:00',name:'Roaders Plus pickup',lat:25.04618,lng:121.51476,duration:'Start',type:'Transport',notes:'Leave earlier than the original plan to reach Shifen near opening time. Confirm fuel, tolls, parking, language and overtime in writing.',official:'https://roadersplushotel.com/en/',maps:'https://www.google.com/maps/search/?api=1&query=Roaders+Plus+Hotel+Taipei+Station'},
{time:'09:15',name:'Shifen Waterfall',lat:25.0495,lng:121.7876,duration:'60 min',type:'Nature',notes:'Early arrival reduces heat and tour-bus density. Wear shoes with grip because paths and platforms may be damp.',official:'https://newtaipei.travel/en/attractions/detail/111403',maps:'https://www.google.com/maps/search/?api=1&query=Shifen+Waterfall'},
{time:'10:35',name:'Shifen Old Street',lat:25.0412,lng:121.7752,duration:'75 min',type:'Sight',notes:'Railway-street walk, one shared sky lantern and one or two snacks. Keep clear of the tracks when trains pass.',official:'https://newtaipei.travel/en/attractions/detail/111735',maps:'https://www.google.com/maps/search/?api=1&query=Shifen+Old+Street'},
{time:'12:35',name:'Golden Waterfall',lat:25.1188,lng:121.8605,duration:'25 min',type:'Nature',notes:'A concise photography stop, not a full attraction block.',official:'https://newtaipei.travel/en/attractions/detail/111998',maps:'https://www.google.com/maps/search/?api=1&query=Golden+Waterfall+Ruifang'},
{time:'13:05',name:'Yin Yang Sea viewpoint',lat:25.1247,lng:121.8639,duration:'20 min',type:'Viewpoint',notes:'Add only if visibility is good and the driver can stop safely. Skip in heavy rain or low cloud.',maps:'https://www.google.com/maps/search/?api=1&query=Yin+Yang+Sea+Viewpoint'},
{time:'13:45',name:'Jiufen Old Street lunch & exploration',lat:25.1099,lng:121.8452,duration:'3 hours',type:'Food',notes:'Eat before the busiest late-afternoon surge, then browse tea, ceramics, snacks and souvenirs. Priorities: fish-ball soup, taro balls and one proper seated meal.',official:'https://newtaipei.travel/en/attractions/detail/111109',maps:'https://www.google.com/maps/search/?api=1&query=Jiufen+Old+Street'},
{time:'16:45',name:'Jiufen tea-house window',lat:25.1097,lng:121.8448,duration:'75 min',type:'Experience',notes:'Reserve a tea-house only if it offers a clear cancellation policy. This is the slow, atmospheric centre of the day, not another checkbox.',maps:'https://www.google.com/maps/search/?api=1&query=Jiufen+tea+house'},
{time:'18:10',name:'Jiufen lantern streets & departure',lat:25.1099,lng:121.8452,duration:'Return',type:'Transport',notes:'Allow a short lantern-lit walk, then leave before fatigue and traffic take control of the evening.',maps:'https://www.google.com/maps/search/?api=1&query=Jiufen+Old+Street'},
{time:'19:45',name:'Roaders Plus Hotel',lat:25.04618,lng:121.51476,duration:'Rest',type:'Hotel',notes:'Yehliu remains excluded. Adding it would convert a good day into a moving queue.',official:'https://roadersplushotel.com/en/',maps:'https://www.google.com/maps/search/?api=1&query=Roaders+Plus+Hotel+Taipei+Station'}]},
{day:4,label:'Mon 23 Aug',title:'Songyan, Taipei 101, Raohe & airport',transport:'MRT + Airport MRT',distance:'East Taipei arc with protected flight buffer',stops:[
{time:'08:30',name:'Breakfast, packing & checkout',lat:25.04618,lng:121.51476,duration:'90 min',type:'Hotel',notes:'Store luggage at reception. Confirm the latest collection time and keep passports, chargers and flight documents in the day bag.',official:'https://roadersplushotel.com/en/',maps:'https://www.google.com/maps/search/?api=1&query=Roaders+Plus+Hotel+Taipei+Station'},
{time:'10:45',name:'Songshan Cultural and Creative Park',lat:25.0436,lng:121.5607,duration:'100 min',type:'Design',notes:'Start with the historic factory spaces and whichever 2027 exhibition is genuinely worthwhile. Current style shops generally open around late morning.',official:'https://www.songshanculturalpark.org/',maps:'https://www.google.com/maps/search/?api=1&query=Songshan+Cultural+and+Creative+Park'},
{time:'12:30',name:'Eslite Spectrum Songyan',lat:25.0441,lng:121.5604,duration:'100 min',type:'Shopping',notes:'Use this for Taiwanese product design, books, stationery, craft and an indoor lunch. It is also the best rain-proof block of the final day.',official:'https://www.eslitecorp.com/eslite/index.jsp?site_id=eslite_en',maps:'https://www.google.com/maps/search/?api=1&query=Eslite+Spectrum+Songyan'},
{time:'14:40',name:'Taipei 101 & Xinyi shopping',lat:25.0338,lng:121.5646,duration:'100 min',type:'Shopping',notes:'Browse Taipei 101 Mall, nearby department stores and food halls. Keep purchases compact because luggage is already packed.',official:'https://www.taipei-101.com.tw/en/',maps:'https://www.google.com/maps/search/?api=1&query=Taipei+101'},
{time:'16:10',name:'Taipei 101 Observatory',lat:25.0339,lng:121.5645,duration:'Optional 75 min',type:'Ticket',notes:'Buy only after checking visibility. The official observatory currently operates daily to 21:00, but recheck 2027 hours and pricing before travel.',official:'https://www.taipei-101.com.tw/en/observatory',tickets:'https://www.taipei-101.com.tw/en/observatory/ticket/information.',maps:'https://www.google.com/maps/search/?api=1&query=Taipei+101+Observatory'},
{time:'17:45',name:'Raohe Night Market early dinner',lat:25.0500,lng:121.5777,duration:'75 min',type:'Food',notes:'Arrive near opening time, eat selectively and leave before the thickest crowd. Priorities: pepper bun, herbal ribs, oyster noodles and one cold drink.',official:'https://www.travel.taipei/en/attraction/details/1691',maps:'https://www.google.com/maps/search/?api=1&query=Raohe+Street+Night+Market'},
{time:'19:15',name:'Collect luggage at Roaders Plus',lat:25.04618,lng:121.51476,duration:'50 min',type:'Hotel',notes:'Final check: passports, EasyCards, power banks, tax-refund documents, liquids and terminal details.',official:'https://roadersplushotel.com/en/',maps:'https://www.google.com/maps/search/?api=1&query=Roaders+Plus+Hotel+Taipei+Station'},
{time:'20:35',name:'Walk to A1 Taipei Main Station',lat:25.04915,lng:121.51415,duration:'35 min',type:'Transport',notes:'Target an Airport MRT around 21:15. Do not build the journey around the final train.',official:'https://www.tymetro.com.tw/tymetro-new/en/_pages/travel-guide/timetable.php',maps:'https://www.google.com/maps/search/?api=1&query=A1+Taipei+Main+Station'},
{time:'22:05',name:'Taoyuan International Airport',lat:25.0777,lng:121.2328,duration:'Flight buffer',type:'Transport',notes:'This preserves more than three hours before the 01:35 departure. Reconfirm airline terminal and check-in cut-off on the day.',official:'https://www.taoyuan-airport.com/',maps:'https://www.google.com/maps/search/?api=1&query=Taoyuan+International+Airport'}]}];
const costs=[['Airport MRT, metro, buses & EasyCards',1000,1400],['Private Jiufen–Shifen driver',4000,6500],['Food, coffee & night markets',7000,9800],['Taipei 101, lantern & tea',1500,3000],['Two SIMs / eSIMs',600,1000],['Taxis, rain & fatigue buffer',1000,1800],['Airport and onboard food',500,1000],['Contingency',1500,2500]];
const auditItems=['Verify checked baggage kilograms for each traveller and direction.','Check whether cabin baggage is separate from checked baggage.','Confirm seat selection, onboard meals and flight terminals.','Open the travel-insurance policy and confirm both travellers, dates, excess and exclusions.','Confirm hotel cancellation terms and same-day luggage storage.','For the private driver, confirm fuel, tolls, parking, language and overtime charges.','Ask eligible shops for tax-refund paperwork on the purchase date.','Recheck all 2027 opening hours because current schedules may change before travel.'];
const apps=[
{icon:'◉',name:'Google Maps',desc:'Saved lists, transit directions and offline area download.',url:'https://maps.google.com/'},
{icon:'M',name:'Taipei Metro Go',desc:'Official Taipei Metro route and service information.',url:'https://english.metro.taipei/'},
{icon:'☂',name:'Taiwan Weather / CWA',desc:'Official radar, warnings and forecast checks.',url:'https://www.cwa.gov.tw/V8/E/'},
{icon:'U',name:'Uber',desc:'Visitor-friendly taxi booking with visible destination.',url:'https://www.uber.com/tw/en/ride/'},
{icon:'B+',name:'Bus+',desc:'Live bus, railway, metro and YouBike information.',url:'https://apps.apple.com/tw/app/bus-bus-railway-ubike/id967861325'},
{icon:'55688',name:'Taiwan Taxi 55688',desc:'Local taxi backup.',url:'https://www.taiwantaxi.com.tw/EN/'},
{icon:'文',name:'Google Translate',desc:'Download Traditional Chinese for offline camera and text translation.',url:'https://translate.google.com/'},
{icon:'T',name:'Trip.com',desc:'Keep booking vouchers, flight changes and hotel details available.',url:'https://sg.trip.com/'},
{icon:'✓',name:'Taoyuan Airport MRT timetable',desc:'Reconfirm the 23 August late-night airport journey.',url:'https://www.tymetro.com.tw/tymetro-new/en/_pages/travel-guide/timetable.php'},
{icon:'!',name:'Taipei travel notices',desc:'Official city attraction and transport updates.',url:'https://www.travel.taipei/en'}];
