const dayColours = {1:'#d94f33',2:'#0f766e',3:'#7c3aed',4:'#b7791f'};
const hotel = { lat:25.04618, lng:121.51476 };
const tripDays = [
{day:1,label:'Fri 20 Aug',title:'Arrival, old Taipei & Ningxia',transport:'Airport MRT + walking',distance:'Easy arrival day',stops:[
{time:'11:45',name:'Taoyuan International Airport',lat:25.0777,lng:121.2328,duration:'Arrival',type:'Transport',notes:'Clear immigration, collect luggage and follow signs to the Airport MRT. Buy one EasyCard each.',official:'https://www.taoyuan-airport.com/',maps:'https://www.google.com/maps/search/?api=1&query=Taoyuan+International+Airport'},
{time:'13:15',name:'Airport MRT to A1 Taipei Main Station',lat:25.04915,lng:121.51415,duration:'35–40 min',type:'Transport',notes:'Take the express train. Use lifts with luggage. Keep a buffer in case immigration is slow.',official:'https://www.tymetro.com.tw/tymetro-new/en/_pages/travel-guide/timetable.php',maps:'https://www.google.com/maps/search/?api=1&query=A1+Taipei+Main+Station'},
{time:'14:10',name:'Roaders Plus Hotel Taipei Station',lat:25.04618,lng:121.51476,duration:'Check-in',type:'Hotel',notes:'Drop luggage or check in. This remains the route anchor throughout the trip.',official:'https://roadersplushotel.com/en/',maps:'https://www.google.com/maps/search/?api=1&query=Roaders+Plus+Hotel+Taipei+Station'},
{time:'14:45',name:'Lao Shan Dong Homemade Noodles',lat:25.0467,lng:121.5105,duration:'60 min',type:'Food',notes:'Late lunch near Taipei Main Station. Try handmade beef noodles, dumplings and braised side dishes.',maps:'https://www.google.com/maps/search/?api=1&query=Lao+Shan+Dong+Homemade+Noodles+Taipei'},
{time:'16:05',name:'North Gate',lat:25.04769,lng:121.51165,duration:'20 min',type:'Sight',notes:'A compact heritage stop and good visual entry into old Taipei.',official:'https://www.travel.taipei/en/attraction/details/429',maps:'https://www.google.com/maps/search/?api=1&query=North+Gate+Taipei'},
{time:'16:40',name:'Dihua Street',lat:25.0556,lng:121.5092,duration:'90 min',type:'Shopping',notes:'Tea, ceramics, fabrics, pantry goods and historic shophouses. Keep room in your bag for design-led gifts.',official:'https://www.travel.taipei/en/attraction/details/1686',maps:'https://www.google.com/maps/search/?api=1&query=Dihua+Street+Taipei'},
{time:'18:10',name:'Dadaocheng Wharf',lat:25.0568,lng:121.5072,duration:'45 min',type:'Sight',notes:'Riverside sunset window. Skip during heavy rain and spend longer on Dihua Street instead.',official:'https://www.travel.taipei/en/attraction/details/1573',maps:'https://www.google.com/maps/search/?api=1&query=Dadaocheng+Wharf'},
{time:'19:10',name:'Ningxia Night Market',lat:25.0555,lng:121.5153,duration:'90 min',type:'Food',notes:'Share small portions: oyster omelette, braised pork rice, taro snacks, grilled squid and peanut ice-cream roll.',official:'https://www.travel.taipei/en/attraction/details/1692',maps:'https://www.google.com/maps/search/?api=1&query=Ningxia+Night+Market'},
{time:'21:00',name:'Return to Roaders Plus',lat:25.04618,lng:121.51476,duration:'Rest',type:'Hotel',notes:'Keep the first evening intentionally light.',official:'https://roadersplushotel.com/en/',maps:'https://www.google.com/maps/search/?api=1&query=Roaders+Plus+Hotel+Taipei+Station'}]},
{day:2,label:'Sat 21 Aug',title:'Heritage, design districts & Ximending',transport:'MRT + walking',distance:'Full city day',stops:[
{time:'08:00',name:'Fu Hang Soy Milk',lat:25.0442,lng:121.5248,duration:'45 min',type:'Food',notes:'Optional. Use a strict 30-minute queue limit. Order soy milk, dan bing, fan tuan or sesame flatbread.',maps:'https://www.google.com/maps/search/?api=1&query=Fu+Hang+Soy+Milk'},
{time:'09:30',name:'Chiang Kai-shek Memorial Hall',lat:25.0346,lng:121.5219,duration:'90 min',type:'Sight',notes:'Explore Liberty Square, gardens and monumental architecture before the heat peaks.',official:'https://www.cksmh.gov.tw/en/',maps:'https://www.google.com/maps/search/?api=1&query=Chiang+Kai-shek+Memorial+Hall'},
{time:'11:30',name:'Yongkang Street',lat:25.0329,lng:121.5290,duration:'110 min',type:'Food',notes:'Choose one main lunch, then add mango ice, tea or a speciality coffee. Avoid turning lunch into a queue marathon.',official:'https://www.travel.taipei/en/attraction/details/1712',maps:'https://www.google.com/maps/search/?api=1&query=Yongkang+Street+Taipei'},
{time:'13:40',name:'Huashan 1914 Creative Park',lat:25.0442,lng:121.5294,duration:'110 min',type:'Design',notes:'Former industrial complex with exhibitions, creative shops, character pop-ups and cafés. Check the programme before travel.',official:'https://www.huashan1914.com/w/huashan1914_en/index',maps:'https://www.google.com/maps/search/?api=1&query=Huashan+1914+Creative+Park'},
{time:'16:00',name:'Zhongshan & Chifeng Street',lat:25.0536,lng:121.5201,duration:'150 min',type:'Shopping',notes:'Independent Taiwanese labels, stationery, lifestyle stores, small galleries and good coffee.',maps:'https://www.google.com/maps/search/?api=1&query=Chifeng+Street+Taipei'},
{time:'19:00',name:'Ximending & The Red House',lat:25.0421,lng:121.5069,duration:'150 min',type:'Shopping',notes:'Streetwear, sneakers, cosmetics, character goods, Red House surroundings and casual dinner grazing.',official:'https://www.redhouse.taipei/en',maps:'https://www.google.com/maps/search/?api=1&query=The+Red+House+Taipei'},
{time:'21:45',name:'Return to Roaders Plus',lat:25.04618,lng:121.51476,duration:'Rest',type:'Hotel',notes:'MRT or a short taxi depending on energy and rain.',official:'https://roadersplushotel.com/en/',maps:'https://www.google.com/maps/search/?api=1&query=Roaders+Plus+Hotel+Taipei+Station'}]},
{day:3,label:'Sun 22 Aug',title:'Private Shifen, Golden Waterfall & Jiufen',transport:'Private driver only',distance:'Approx. 8–11 hours',stops:[
{time:'08:30',name:'Roaders Plus pickup',lat:25.04618,lng:121.51476,duration:'Start',type:'Transport',notes:'Private car only, not a group tour. Confirm petrol, parking, tolls, language and overtime in writing.',official:'https://roadersplushotel.com/en/',maps:'https://www.google.com/maps/search/?api=1&query=Roaders+Plus+Hotel+Taipei+Station'},
{time:'10:00',name:'Shifen Waterfall',lat:25.0495,lng:121.7876,duration:'60 min',type:'Nature',notes:'Wear shoes with grip. Paths can be damp. Allow time for the viewing platforms.',official:'https://newtaipei.travel/en/attractions/detail/111403',maps:'https://www.google.com/maps/search/?api=1&query=Shifen+Waterfall'},
{time:'11:20',name:'Shifen Old Street',lat:25.0412,lng:121.7752,duration:'90 min',type:'Sight',notes:'Railway-street walk, one shared sky lantern and light snacks. Keep clear of the tracks when trains pass.',official:'https://newtaipei.travel/en/attractions/detail/111735',maps:'https://www.google.com/maps/search/?api=1&query=Shifen+Old+Street'},
{time:'13:20',name:'Golden Waterfall',lat:25.1188,lng:121.8605,duration:'30 min',type:'Nature',notes:'A scenic photography stop rather than a long excursion.',official:'https://newtaipei.travel/en/attractions/detail/111998',maps:'https://www.google.com/maps/search/?api=1&query=Golden+Waterfall+Ruifang'},
{time:'14:20',name:'Jiufen Old Street',lat:25.1099,lng:121.8452,duration:'4 hours',type:'Food',notes:'Late lunch, old-street browsing, taro balls, fish-ball soup, souvenir shops and a tea-house window around 16:30.',official:'https://newtaipei.travel/en/attractions/detail/111109',maps:'https://www.google.com/maps/search/?api=1&query=Jiufen+Old+Street'},
{time:'18:30',name:'Jiufen evening departure',lat:25.1099,lng:121.8452,duration:'Return',type:'Transport',notes:'Leave after the lanterns come on, before fatigue turns the day into gravel.',maps:'https://www.google.com/maps/search/?api=1&query=Jiufen+Old+Street'},
{time:'20:00',name:'Roaders Plus Hotel',lat:25.04618,lng:121.51476,duration:'Rest',type:'Hotel',notes:'Yehliu is intentionally excluded to keep the day comfortable.',official:'https://roadersplushotel.com/en/',maps:'https://www.google.com/maps/search/?api=1&query=Roaders+Plus+Hotel+Taipei+Station'}]},
{day:4,label:'Mon 23 Aug',title:'Songyan, Taipei 101 & airport',transport:'MRT + Airport MRT',distance:'Checkout + late departure',stops:[
{time:'09:00',name:'Breakfast, packing & checkout',lat:25.04618,lng:121.51476,duration:'90 min',type:'Hotel',notes:'Store luggage at the hotel after checkout. Confirm same-day collection time with reception.',official:'https://roadersplushotel.com/en/',maps:'https://www.google.com/maps/search/?api=1&query=Roaders+Plus+Hotel+Taipei+Station'},
{time:'11:00',name:'Songshan Cultural and Creative Park',lat:25.0436,lng:121.5607,duration:'90 min',type:'Design',notes:'Historic industrial buildings, courtyards, exhibitions and design stores.',official:'https://www.songshanculturalpark.org/en',maps:'https://www.google.com/maps/search/?api=1&query=Songshan+Cultural+and+Creative+Park'},
{time:'12:30',name:'Eslite Spectrum Songyan',lat:25.0441,lng:121.5604,duration:'110 min',type:'Shopping',notes:'Taiwanese design, books, stationery, craft, lifestyle products and food.',official:'https://www.eslitecorp.com/eslite/index.jsp?site_id=eslite_en',maps:'https://www.google.com/maps/search/?api=1&query=Eslite+Spectrum+Songyan'},
{time:'14:40',name:'Taipei 101 & Xinyi shopping',lat:25.0338,lng:121.5646,duration:'3 hours',type:'Shopping',notes:'Taipei 101 Mall, department stores, food halls and design gifts. Keep the observatory weather-dependent.',official:'https://www.taipei-101.com.tw/en/',maps:'https://www.google.com/maps/search/?api=1&query=Taipei+101'},
{time:'15:30',name:'Taipei 101 Observatory',lat:25.0339,lng:121.5645,duration:'Optional 90 min',type:'Ticket',notes:'Buy only when visibility is worthwhile. Do not let a cloud ceiling invoice you.',official:'https://www.taipei-101.com.tw/en/observatory/ticket',tickets:'https://www.taipei-101.com.tw/en/observatory/ticket',maps:'https://www.google.com/maps/search/?api=1&query=Taipei+101+Observatory'},
{time:'18:00',name:'Early final dinner',lat:25.0345,lng:121.5641,duration:'75 min',type:'Food',notes:'Keep the airport schedule protected. Skip any restaurant quoting an excessive wait.',maps:'https://www.google.com/maps/search/?api=1&query=restaurants+near+Taipei+101'},
{time:'19:30',name:'Collect luggage at Roaders Plus',lat:25.04618,lng:121.51476,duration:'45 min',type:'Hotel',notes:'Final bag check: passports, chargers, EasyCards, tax-refund paperwork and liquids.',official:'https://roadersplushotel.com/en/',maps:'https://www.google.com/maps/search/?api=1&query=Roaders+Plus+Hotel+Taipei+Station'},
{time:'20:45',name:'Walk to A1 Taipei Main Station',lat:25.04915,lng:121.51415,duration:'30 min',type:'Transport',notes:'Target an Airport MRT around 21:15–21:30. Do not rely on the final train.',official:'https://www.tymetro.com.tw/tymetro-new/en/_pages/travel-guide/timetable.php',maps:'https://www.google.com/maps/search/?api=1&query=A1+Taipei+Main+Station'},
{time:'22:10',name:'Taoyuan International Airport',lat:25.0777,lng:121.2328,duration:'Flight buffer',type:'Transport',notes:'Allow ample time for the 01:35 flight on 24 August. Reconfirm terminal and airline check-in requirements.',official:'https://www.taoyuan-airport.com/',maps:'https://www.google.com/maps/search/?api=1&query=Taoyuan+International+Airport'}]}];
const costs=[['Airport MRT, metro, buses & EasyCards',1000,1400],['Private Jiufen–Shifen driver',4000,6500],['Food, coffee & night markets',6500,9000],['Taipei 101, lantern & tea',1500,2800],['Two SIMs / eSIMs',600,1000],['Taxis, rain & fatigue buffer',1000,1800],['Airport and onboard food',500,1000],['Contingency',1500,2500]];
const auditItems=['Verify checked baggage kilograms for each traveller and direction.','Check whether cabin baggage is separate from checked baggage.','Confirm seat selection, onboard meals and flight terminals.','Open the travel-insurance policy and confirm both travellers, dates, excess and exclusions.','Confirm hotel cancellation terms and same-day luggage storage.','For the private driver, confirm fuel, tolls, parking, language and overtime charges.','Ask eligible shops for tax-refund paperwork on the purchase date.'];
const apps=[
{icon:'◉',name:'Google Maps',desc:'Saved lists, transit directions and offline area download.',url:'https://maps.google.com/'},
{icon:'M',name:'Taipei Metro Go',desc:'Official Taipei Metro route and service information.',url:'https://english.metro.taipei/'},
{icon:'☂',name:'Taiwan Weather / CWA',desc:'Official radar, warnings and forecast checks.',url:'https://www.cwa.gov.tw/V8/E/'},
{icon:'U',name:'Uber',desc:'Visitor-friendly taxi booking with visible destination.',url:'https://www.uber.com/tw/en/ride/'},
{icon:'B+',name:'Bus+',desc:'Live bus, railway, metro and YouBike information.',url:'https://apps.apple.com/tw/app/bus-bus-railway-ubike/id967861325'},
{icon:'55688',name:'Taiwan Taxi 55688',desc:'Local taxi backup.',url:'https://www.taiwantaxi.com.tw/EN/'},
{icon:'文',name:'Google Translate',desc:'Download Traditional Chinese for offline camera and text translation.',url:'https://translate.google.com/'},
{icon:'T',name:'Trip.com',desc:'Keep booking vouchers, flight changes and hotel details available.',url:'https://sg.trip.com/'},
{icon:'✓',name:'Taoyuan Airport MRT timetable',desc:'Reconfirm the 23 August late-night airport journey.',url:'https://www.tymetro.com.tw/tymetro-new/en/_pages/travel-guide/timetable.php'},
{icon:'!',name:'Taipei travel notices',desc:'Official city attraction and transport updates.',url:'https://www.travel.taipei/en'}];
